global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

#pull from gateway, instead of application
scrape_configs:
  - job_name: pushgateway
    static_configs:
      - targets: [ 'pushgateway:9091' ]
        labels:
          instance: pushgateway
